
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IDS348_FinalProject
{

using System;
    using System.Collections.Generic;
    
public partial class Follower
{

    public int FollowerID { get; set; }

    public int FollowingID { get; set; }

    public System.DateTime FollowDate { get; set; }



    public virtual User User { get; set; }

}

}
