//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS348_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int MessageID { get; set; }
        public int RemitenteID { get; set; }
        public int DestinatarioID { get; set; }
        public string Message_text { get; set; }
        public System.DateTime Date_sent { get; set; }
        public bool Message_read { get; set; }
        public bool TieneAdjunto { get; set; }
        public byte[] Adjunto { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
