
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IDS348_FinalProject
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Post()
    {

        this.Comments = new HashSet<Comment>();

        this.Saves = new HashSet<Save>();

        this.Hashtags = new HashSet<Hashtag>();

    }


    public int PostID { get; set; }

    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Text { get; set; }

    public System.DateTime PublicationDate { get; set; }

    public string TipoContenido { get; set; }

    public string URLContenido { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comments { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Save> Saves { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Hashtag> Hashtags { get; set; }

}

}
